import {
  Rss,
  Users,
  Sparkles,
  Briefcase,
  FolderKanban,
  MessageSquare,
  Rocket,
  UserSearch,
  Star,
  TrendingUp,
  Building2,
  User,
  Building,
  ShieldCheck,
  Network,
  UsersRound,
  PlayCircle,
  Newspaper,
  BookOpen,
  FileBarChart,
  Quote,
  Video,
  LifeBuoy,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  type LucideIcon,
} from 'lucide-react';

const PUBLIC_ICONS: Record<string, LucideIcon> = {
  Rss,
  Users,
  Sparkles,
  Briefcase,
  FolderKanban,
  MessageSquare,
  Rocket,
  UserSearch,
  Star,
  TrendingUp,
  Building2,
  User,
  Building,
  ShieldCheck,
  Network,
  UsersRound,
  PlayCircle,
  Newspaper,
  BookOpen,
  FileBarChart,
  Quote,
  Video,
  LifeBuoy,
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
};

export function PublicIcon({ name, className }: { name?: string; className?: string }) {
  const Cmp = (name && PUBLIC_ICONS[name]) || Sparkles;
  return <Cmp className={className} strokeWidth={1.75} />;
}
