import {
  Activity,
  Users,
  Folder,
  Briefcase,
  Sparkles,
  FileText,
  Users2,
  BarChart3,
  MoreHorizontal,
  UserCheck,
  AtSign,
  Bookmark,
  File,
  Edit3,
  Clock,
  Link as LinkIcon,
  UserPlus,
  Mail,
  Building2,
  Calendar,
  Share2,
  LayoutGrid,
  CheckSquare,
  Flag,
  Paperclip,
  CheckCircle2,
  Search,
  Send,
  Zap,
  PlusCircle,
  Rocket,
  Award,
  ShieldCheck,
  Heart,
  Compass,
  History,
  SlidersHorizontal,
  DollarSign,
  Settings,
  Bell,
  MessageSquare,
  Command,
  Sparkle,
  ChevronDown,
  X,
  Check,
  Plus,
  Image as ImageIcon,
  Video,
  ListChecks,
  Smile,
  Globe,
  ThumbsUp,
  MessageCircle,
  Repeat2,
  Forward,
  MoreVertical,
  Pin,
  ArrowLeft,
  ArrowRight,
  LogOut,
  Shield,
  KeyRound,
  Moon,
  Sun,
  BellRing,
  Inbox,
  Star,
  Trash2,
  Filter,
  ArrowUpDown,
  Grid3x3,
  List as ListIcon,
  Loader2,
  Target,
  Upload,
  TrendingUp,
  Ban,
  GraduationCap,
  LifeBuoy,
  Crown,
  CreditCard,
  Layers,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  users: Users,
  folder: Folder,
  briefcase: Briefcase,
  sparkles: Sparkles,
  'file-text': FileText,
  'users-round': Users2,
  'bar-chart': BarChart3,
  'more-horizontal': MoreHorizontal,
  'user-check': UserCheck,
  'at-sign': AtSign,
  bookmark: Bookmark,
  file: File,
  'edit-3': Edit3,
  clock: Clock,
  link: LinkIcon,
  'user-plus': UserPlus,
  mail: Mail,
  building: Building2,
  calendar: Calendar,
  'share-2': Share2,
  'layout-grid': LayoutGrid,
  'check-square': CheckSquare,
  flag: Flag,
  paperclip: Paperclip,
  'check-circle': CheckCircle2,
  search: Search,
  send: Send,
  zap: Zap,
  'plus-circle': PlusCircle,
  rocket: Rocket,
  award: Award,
  'shield-check': ShieldCheck,
  heart: Heart,
  compass: Compass,
  history: History,
  sliders: SlidersHorizontal,
  'dollar-sign': DollarSign,
  settings: Settings,
  bell: Bell,
  'message-square': MessageSquare,
  video: Video,
  globe: Globe,
  target: Target,
  upload: Upload,
  'trending-up': TrendingUp,
  ban: Ban,
  'graduation-cap': GraduationCap,
  'life-buoy': LifeBuoy,
  crown: Crown,
  'credit-card': CreditCard,
  layers: Layers,
};

export function NavIcon({ name, className }: { name?: string | null; className?: string }) {
  const Cmp = (name && ICONS[name]) || Sparkles;
  return <Cmp className={className} strokeWidth={1.75} />;
}

export {
  Command,
  Sparkle,
  ChevronDown,
  X,
  Check,
  Plus,
  ImageIcon,
  Video,
  ListChecks,
  Smile,
  Globe,
  ThumbsUp,
  MessageCircle,
  Repeat2,
  Forward,
  MoreVertical,
  Pin,
  ArrowLeft,
  ArrowRight,
  LogOut,
  Shield,
  KeyRound,
  Moon,
  Sun,
  BellRing,
  Inbox,
  Star,
  Trash2,
  Filter,
  ArrowUpDown,
  Grid3x3,
  ListIcon,
  Loader2,
  Search,
  Bell,
  Users,
  Briefcase,
  Folder,
  FileText,
  Building2,
  Calendar,
  Bookmark,
};
