'use client';

// Backed by GET /ai-usage — apps/api's AI governance module. Aggregates every
// real ai_usage row generated by this user's own activity across the whole
// platform (Copilot generations, smart replies, conversation summaries,
// message safety classifications). There is NO multi-user/team concept on
// this endpoint — a brand-new/low-activity account will legitimately show
// small or zero numbers.

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';

export type AiUsageByModel = { model: string; count: number };
export type AiUsageTrendPoint = { day: string; requests: number; tokens: number };

export type AiUsageSummary = {
  totalRequests: number;
  totalTokens: number;
  totalCost: number;
  successRate: number; // 0-1
  avgLatencyMs: number;
  byModel: AiUsageByModel[];
  trend: AiUsageTrendPoint[];
};

export type AiUsageDateRange = { from: string; to: string };

/** Default range: last 30 days (matches the backend's own default when from/to are omitted). */
export function defaultAiUsageRange(): AiUsageDateRange {
  const to = new Date();
  const from = new Date(to);
  from.setDate(from.getDate() - 30);
  return { from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) };
}

export function useAiUsage(range: AiUsageDateRange) {
  return useQuery({
    queryKey: ['ai-usage', range.from, range.to],
    queryFn: async () => {
      const { data } = await api.get<{ data: AiUsageSummary }>('/ai-usage', {
        params: { from: range.from, to: range.to },
      });
      return data.data;
    },
    staleTime: 30_000,
  });
}
