import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import usersRoutes from '../modules/users/users.routes.js';
import profilesRoutes from '../modules/profiles/profiles.routes.js';
import connectionsRoutes from '../modules/connections/connections.routes.js';
import postsRoutes from '../modules/posts/posts.routes.js';
import jobsRoutes from '../modules/jobs/jobs.routes.js';
import applicationsRoutes from '../modules/applications/applications.routes.js';
import messagingRoutes from '../modules/messaging/messaging.routes.js';
import messageRequestsRoutes from '../modules/messaging/messageRequests.routes.js';
import messagingSettingsRoutes from '../modules/messaging/messagingSettings.routes.js';
import callsRoutes from '../modules/calls/calls.routes.js';
import meetingsRoutes from '../modules/meetings/meetings.routes.js';
import presenceRoutes from '../modules/presence/presence.routes.js';
import notificationsRoutes from '../modules/notifications/notifications.routes.js';
import searchRoutes from '../modules/search/search.routes.js';
import securityRoutes from '../modules/security/security.routes.js';
import mfaRoutes from '../modules/mfa/mfa.routes.js';
import passkeysRoutes from '../modules/passkeys/passkeys.routes.js';
import accountIntentRoutes from '../modules/account-intent/account-intent.routes.js';
import accountRecoveryRoutes from '../modules/account-recovery/account-recovery.routes.js';
import workspacesRoutes from '../modules/workspaces/workspaces.routes.js';
import navigationRoutes from '../modules/navigation/navigation.routes.js';
import publicContentRoutes from '../modules/public-content/public-content.routes.js';
import savedItemsRoutes from '../modules/saved-items/saved-items.routes.js';
import activityRoutes from '../modules/activity/activity.routes.js';
import copilotRoutes from '../modules/copilot/copilot.routes.js';
import adsRoutes from '../modules/ads/ads.routes.js';
import {
  actionsRouter as aiActionsRoutes,
  tasksRouter as aiTasksRoutes,
  memoryRouter as aiMemoryRoutes,
  personalisationRouter as aiPersonalisationRoutes,
  modelPreferencesRouter as aiModelPreferencesRoutes,
  usageRouter as aiUsageRoutes,
  auditRouter as aiAuditRoutes,
  promptsRouter as aiPromptsRoutes,
} from '../modules/ai/ai.routes.js';
import gigsRoutes from '../modules/gigs/gigs.routes.js';
import groupsRoutes from '../modules/groups/groups.routes.js';
import videosRoutes from '../modules/videos/videos.routes.js';
import { talentRouter, companiesRouter, jobsRouter as publicJobsRouter, postsRouter as publicPostsRouter } from '../modules/public-directory/public-directory.routes.js';
import billingRoutes, { authRouter as billingAuthRoutes } from '../modules/billing/billing.routes.js';
import helpCentreRoutes from '../modules/help-centre/help-centre.routes.js';
import legalRoutes from '../modules/legal/legal.routes.js';
import resourcesRoutes from '../modules/resources/resources.routes.js';
import personalizationRoutes from '../modules/personalization/personalization.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import onboardingRoutes from '../modules/onboarding/onboarding.routes.js';
import importsRoutes from '../modules/imports/imports.routes.js';
import contactsRoutes from '../modules/contacts/contacts.routes.js';
import setupChecklistRoutes from '../modules/setup-checklist/setup-checklist.routes.js';
import productTourRoutes from '../modules/product-tour/productTour.routes.js';
import tasksRoutes from '../modules/tasks/tasks.routes.js';
import calendarRoutes from '../modules/calendar/calendar.routes.js';
import projectsRoutes from '../modules/projects/projects.routes.js';
import pmProjectsRoutes from '../modules/pm-projects/pmProjects.routes.js';
import disputesRoutes from '../modules/disputes/disputes.routes.js';
import taxonomiesRoutes from '../modules/taxonomies/taxonomies.routes.js';
import jobAlertsRoutes from '../modules/job-alerts/jobAlerts.routes.js';
import screeningRoutes from '../modules/screening/screening.routes.js';
import assessmentsRoutes from '../modules/assessments/assessments.routes.js';
import interviewsRoutes from '../modules/interviews/interviews.routes.js';
import offersRoutes from '../modules/offers/offers.routes.js';
import sponsoredJobsRoutes from '../modules/sponsored-jobs/sponsoredJobs.routes.js';
import hireHandoffsRoutes from '../modules/hire-handoffs/hireHandoffs.routes.js';
import podcastsRoutes from '../modules/podcasts/podcasts.routes.js';
import webinarsRoutes from '../modules/webinars/webinars.routes.js';
import articlesRoutes from '../modules/articles/articles.routes.js';
import newslettersRoutes from '../modules/newsletters/newsletters.routes.js';
import hashtagsRoutes from '../modules/hashtags/hashtags.routes.js';
import trendingRoutes from '../modules/trending/trending.routes.js';
import professionalProfileRoutes from '../modules/professional-profile/professionalProfile.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import moderationRoutes from '../modules/moderation/moderation.routes.js';
import businessWorkspaceRoutes from '../modules/business-workspace/business-workspace.routes.js';
import teamsRoutes from '../modules/teams/teams.routes.js';
import departmentsRoutes from '../modules/departments/departments.routes.js';
import businessMembersRoutes from '../modules/business-members/business-members.routes.js';
import spendRoutes from '../modules/spend/spend.routes.js';
import hiringRoutes from '../modules/hiring/hiring.routes.js';
import talentDiscoveryRoutes from '../modules/talent-discovery/talent-discovery.routes.js';
import talentPoolsRoutes from '../modules/talent-pools/talent-pools.routes.js';
import shortlistsRoutes from '../modules/shortlists/shortlists.routes.js';
import businessInterviewsRoutes from '../modules/business-interviews/business-interviews.routes.js';
import businessOffersRoutes from '../modules/business-offers/business-offers.routes.js';
import businessProjectsRoutes from '../modules/business-projects/business-projects.routes.js';
import workforcePlanningRoutes from '../modules/workforce-planning/workforce-planning.routes.js';
import businessApplicantsRoutes from '../modules/business-applicants/business-applicants.routes.js';
import businessAnalyticsRoutes from '../modules/business-analytics/business-analytics.routes.js';
import recruiterSeatsRoutes from '../modules/recruiter-seats/recruiter-seats.routes.js';
import candidateSearchRoutes from '../modules/candidate-search/candidate-search.routes.js';
import candidateSavesRoutes from '../modules/candidate-saves/candidate-saves.routes.js';
import candidateDetailRoutes from '../modules/candidate-detail/candidate-detail.routes.js';
import candidateNotesRoutes from '../modules/candidate-notes/candidate-notes.routes.js';
import recruiterTalentPoolsRoutes from '../modules/recruiter-talent-pools/recruiter-talent-pools.routes.js';
import recruiterShortlistsRoutes from '../modules/recruiter-shortlists/recruiter-shortlists.routes.js';
import recruiterProjectsRoutes from '../modules/recruiter-projects/recruiter-projects.routes.js';
import recruiterSearchAlertsRoutes from '../modules/recruiter-search-alerts/recruiter-search-alerts.routes.js';
import recruiterInboxRoutes from '../modules/recruiter-inbox/recruiter-inbox.routes.js';
import recruiterAnalyticsRoutes from '../modules/recruiter-analytics/recruiter-analytics.routes.js';
import recruiterHomeRoutes from '../modules/recruiter-home/recruiter-home.routes.js';
import recruiterUpgradeRoutes from '../modules/recruiter-upgrade/recruiter-upgrade.routes.js';
import recruiterProHomeRoutes from '../modules/recruiter-pro-home/recruiter-pro-home.routes.js';
import recruiterProProjectsRoutes from '../modules/recruiter-pro-projects/recruiter-pro-projects.routes.js';
import advancedCandidateSearchRoutes from '../modules/advanced-candidate-search/advanced-candidate-search.routes.js';
import aiCandidateMatchingRoutes from '../modules/ai-candidate-matching/ai-candidate-matching.routes.js';
import pipelineRoutes from '../modules/pipeline/pipeline.routes.js';
import bulkOutreachRoutes from '../modules/bulk-outreach/bulk-outreach.routes.js';
import outreachTemplatesRoutes from '../modules/outreach-templates/outreach-templates.routes.js';
import sequencesRoutes from '../modules/sequences/sequences.routes.js';
import teamCollaborationRoutes from '../modules/team-collaboration/team-collaboration.routes.js';
import candidateActivityRoutes from '../modules/candidate-activity/candidate-activity.routes.js';
import advancedAlertsRoutes from '../modules/advanced-alerts/advanced-alerts.routes.js';
import recruiterProAnalyticsRoutes from '../modules/recruiter-pro-analytics/recruiter-pro-analytics.routes.js';
import atsIntegrationsRoutes from '../modules/ats-integrations/ats-integrations.routes.js';
import crmRoutes from '../modules/crm/crm.routes.js';
import intelligenceRoutes from '../modules/intelligence/intelligence.routes.js';

const router = Router();

router.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/profiles', profilesRoutes);
router.use('/connections', connectionsRoutes);
router.use('/feed', postsRoutes);
router.use('/jobs', jobsRoutes);
router.use('/applications', applicationsRoutes);
router.use('/conversations', messagingRoutes);
router.use('/message-requests', messageRequestsRoutes);
router.use('/messaging-settings', messagingSettingsRoutes);
router.use('/calls', callsRoutes);
router.use('/meetings', meetingsRoutes);
router.use('/presence', presenceRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/search', searchRoutes);
router.use('/security', securityRoutes);
router.use('/auth/mfa', mfaRoutes);
router.use('/auth/passkeys', passkeysRoutes);
router.use('/account-intent', accountIntentRoutes);
router.use('/account-recovery', accountRecoveryRoutes);
router.use('/account-contexts', workspacesRoutes);
router.use('/navigation', navigationRoutes);
router.use('/public', publicContentRoutes);
router.use('/public/gigs', gigsRoutes);
router.use('/public/groups', groupsRoutes);
router.use('/public/videos', videosRoutes);
router.use('/public/talent', talentRouter);
router.use('/public/companies', companiesRouter);
router.use('/public/jobs', publicJobsRouter);
router.use('/public/posts', publicPostsRouter);
router.use('/public/billing', billingRoutes);
router.use('/billing', billingAuthRoutes);
router.use('/public/help-centre', helpCentreRoutes);
router.use('/public/legal', legalRoutes);
router.use('/public/resources', resourcesRoutes);
router.use('/public/personalization', personalizationRoutes);
router.use('/public/analytics', analyticsRoutes);
router.use('/saved-items', savedItemsRoutes);
router.use('/activity', activityRoutes);
router.use('/copilot', copilotRoutes);
router.use('/ads', adsRoutes);
router.use('/ai-actions', aiActionsRoutes);
router.use('/ai-tasks', aiTasksRoutes);
router.use('/ai-memory', aiMemoryRoutes);
router.use('/ai-personalisation', aiPersonalisationRoutes);
router.use('/ai-model-preferences', aiModelPreferencesRoutes);
router.use('/ai-usage', aiUsageRoutes);
router.use('/ai-audit', aiAuditRoutes);
router.use('/ai-prompts', aiPromptsRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/imports', importsRoutes);
router.use('/contacts', contactsRoutes);
router.use('/setup-checklist', setupChecklistRoutes);
router.use('/product-tour', productTourRoutes);
router.use('/tasks', tasksRoutes);
router.use('/calendar', calendarRoutes);
router.use('/projects', projectsRoutes);
router.use('/pm-projects', pmProjectsRoutes);
router.use('/disputes', disputesRoutes);
router.use('/taxonomies', taxonomiesRoutes);
router.use('/job-alerts', jobAlertsRoutes);
router.use('/screening', screeningRoutes);
router.use('/assessments', assessmentsRoutes);
router.use('/interviews', interviewsRoutes);
router.use('/offers', offersRoutes);
router.use('/sponsored-jobs', sponsoredJobsRoutes);
router.use('/hire-handoffs', hireHandoffsRoutes);
router.use('/podcasts', podcastsRoutes);
router.use('/webinars', webinarsRoutes);
router.use('/articles', articlesRoutes);
router.use('/newsletters', newslettersRoutes);
router.use('/hashtags', hashtagsRoutes);
router.use('/trending', trendingRoutes);
router.use('/professional-profile', professionalProfileRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/moderation', moderationRoutes);
router.use('/business-workspace', businessWorkspaceRoutes);
router.use('/teams', teamsRoutes);
router.use('/departments', departmentsRoutes);
router.use('/business-members', businessMembersRoutes);
router.use('/spend', spendRoutes);
router.use('/hiring', hiringRoutes);
router.use('/talent-discovery', talentDiscoveryRoutes);
router.use('/talent-pools', talentPoolsRoutes);
router.use('/shortlists', shortlistsRoutes);
router.use('/business-interviews', businessInterviewsRoutes);
router.use('/business-offers', businessOffersRoutes);
router.use('/business-projects', businessProjectsRoutes);
router.use('/workforce-planning', workforcePlanningRoutes);
router.use('/business-applicants', businessApplicantsRoutes);
router.use('/business-analytics', businessAnalyticsRoutes);

// Domain 20: Recruiter Standard.
router.use('/recruiter-seats', recruiterSeatsRoutes);
router.use('/candidate-search', candidateSearchRoutes);
router.use('/candidate-saves', candidateSavesRoutes);
router.use('/candidate-detail', candidateDetailRoutes);
router.use('/candidate-notes', candidateNotesRoutes);
router.use('/recruiter-talent-pools', recruiterTalentPoolsRoutes);
router.use('/recruiter-shortlists', recruiterShortlistsRoutes);
router.use('/recruiter-projects', recruiterProjectsRoutes);
router.use('/recruiter-search-alerts', recruiterSearchAlertsRoutes);
router.use('/recruiter-inbox', recruiterInboxRoutes);
router.use('/recruiter-analytics', recruiterAnalyticsRoutes);
router.use('/recruiter-home', recruiterHomeRoutes);
router.use('/recruiter-upgrade', recruiterUpgradeRoutes);

// Domain 21: Recruiter Pro.
router.use('/recruiter-pro-home', recruiterProHomeRoutes);
router.use('/recruiter-pro-projects', recruiterProProjectsRoutes);
router.use('/advanced-candidate-search', advancedCandidateSearchRoutes);
router.use('/ai-candidate-matching', aiCandidateMatchingRoutes);
router.use('/pipeline', pipelineRoutes);
router.use('/bulk-outreach', bulkOutreachRoutes);
router.use('/outreach-templates', outreachTemplatesRoutes);
router.use('/sequences', sequencesRoutes);
router.use('/recruiter-collaboration', teamCollaborationRoutes);
router.use('/candidate-activity', candidateActivityRoutes);
router.use('/advanced-alerts', advancedAlertsRoutes);
router.use('/recruiter-pro-analytics', recruiterProAnalyticsRoutes);
router.use('/ats-integrations', atsIntegrationsRoutes);

// Domain 24: CRM, Leads, Accounts & Relationship Operations.
router.use('/crm', crmRoutes);

// Domain 26: Machine Learning, Matching, Ranking & Intelligence.
router.use('/intelligence', intelligenceRoutes);

export default router;
