import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import usersRoutes from '../modules/users/users.routes.js';
import profilesRoutes from '../modules/profiles/profiles.routes.js';
import connectionsRoutes from '../modules/connections/connections.routes.js';
import postsRoutes from '../modules/posts/posts.routes.js';
import jobsRoutes from '../modules/jobs/jobs.routes.js';
import applicationsRoutes from '../modules/applications/applications.routes.js';
import messagingRoutes from '../modules/messaging/messaging.routes.js';
import messageRequestsRoutes from '../modules/messaging/messageRequests.routes.js';
import messagingSettingsRoutes from '../modules/messaging/messagingSettings.routes.js';
import callsRoutes from '../modules/calls/calls.routes.js';
import meetingsRoutes from '../modules/meetings/meetings.routes.js';
import presenceRoutes from '../modules/presence/presence.routes.js';
import notificationsRoutes from '../modules/notifications/notifications.routes.js';
import searchRoutes from '../modules/search/search.routes.js';
import securityRoutes from '../modules/security/security.routes.js';
import mfaRoutes from '../modules/mfa/mfa.routes.js';
import passkeysRoutes from '../modules/passkeys/passkeys.routes.js';
import accountIntentRoutes from '../modules/account-intent/account-intent.routes.js';
import accountRecoveryRoutes from '../modules/account-recovery/account-recovery.routes.js';
import workspacesRoutes from '../modules/workspaces/workspaces.routes.js';
import navigationRoutes from '../modules/navigation/navigation.routes.js';
import publicContentRoutes from '../modules/public-content/public-content.routes.js';
import savedItemsRoutes from '../modules/saved-items/saved-items.routes.js';
import activityRoutes from '../modules/activity/activity.routes.js';
import copilotRoutes from '../modules/copilot/copilot.routes.js';
import adsRoutes from '../modules/ads/ads.routes.js';
import {
  actionsRouter as aiActionsRoutes,
  tasksRouter as aiTasksRoutes,
  memoryRouter as aiMemoryRoutes,
  personalisationRouter as aiPersonalisationRoutes,
  modelPreferencesRouter as aiModelPreferencesRoutes,
  usageRouter as aiUsageRoutes,
  auditRouter as aiAuditRoutes,
  promptsRouter as aiPromptsRoutes,
} from '../modules/ai/ai.routes.js';
import gigsRoutes from '../modules/gigs/gigs.routes.js';
import groupsRoutes from '../modules/groups/groups.routes.js';
import videosRoutes from '../modules/videos/videos.routes.js';
import { talentRouter, companiesRouter, jobsRouter as publicJobsRouter, postsRouter as publicPostsRouter } from '../modules/public-directory/public-directory.routes.js';
import billingRoutes, { authRouter as billingAuthRoutes } from '../modules/billing/billing.routes.js';
import helpCentreRoutes from '../modules/help-centre/help-centre.routes.js';
import legalRoutes from '../modules/legal/legal.routes.js';
import resourcesRoutes from '../modules/resources/resources.routes.js';
import personalizationRoutes from '../modules/personalization/personalization.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import onboardingRoutes from '../modules/onboarding/onboarding.routes.js';
import importsRoutes from '../modules/imports/imports.routes.js';
import contactsRoutes from '../modules/contacts/contacts.routes.js';
import setupChecklistRoutes from '../modules/setup-checklist/setup-checklist.routes.js';
import productTourRoutes from '../modules/product-tour/productTour.routes.js';
import tasksRoutes from '../modules/tasks/tasks.routes.js';
import calendarRoutes from '../modules/calendar/calendar.routes.js';
import projectsRoutes from '../modules/projects/projects.routes.js';
import pmProjectsRoutes from '../modules/pm-projects/pmProjects.routes.js';
import disputesRoutes from '../modules/disputes/disputes.routes.js';
import jobAlertsRoutes from '../modules/job-alerts/jobAlerts.routes.js';
import screeningRoutes from '../modules/screening/screening.routes.js';
import assessmentsRoutes from '../modules/assessments/assessments.routes.js';
import interviewsRoutes from '../modules/interviews/interviews.routes.js';
import offersRoutes from '../modules/offers/offers.routes.js';
import sponsoredJobsRoutes from '../modules/sponsored-jobs/sponsoredJobs.routes.js';
import hireHandoffsRoutes from '../modules/hire-handoffs/hireHandoffs.routes.js';
import podcastsRoutes from '../modules/podcasts/podcasts.routes.js';
import webinarsRoutes from '../modules/webinars/webinars.routes.js';
import articlesRoutes from '../modules/articles/articles.routes.js';
import newslettersRoutes from '../modules/newsletters/newsletters.routes.js';
import hashtagsRoutes from '../modules/hashtags/hashtags.routes.js';
import trendingRoutes from '../modules/trending/trending.routes.js';
import professionalProfileRoutes from '../modules/professional-profile/professionalProfile.routes.js';
import adminRoutes from '../modules/admin/admin.routes.js';
import moderationRoutes from '../modules/moderation/moderation.routes.js';

const router = Router();

router.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/profiles', profilesRoutes);
router.use('/connections', connectionsRoutes);
router.use('/feed', postsRoutes);
router.use('/jobs', jobsRoutes);
router.use('/applications', applicationsRoutes);
router.use('/conversations', messagingRoutes);
router.use('/message-requests', messageRequestsRoutes);
router.use('/messaging-settings', messagingSettingsRoutes);
router.use('/calls', callsRoutes);
router.use('/meetings', meetingsRoutes);
router.use('/presence', presenceRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/search', searchRoutes);
router.use('/security', securityRoutes);
router.use('/auth/mfa', mfaRoutes);
router.use('/auth/passkeys', passkeysRoutes);
router.use('/account-intent', accountIntentRoutes);
router.use('/account-recovery', accountRecoveryRoutes);
router.use('/account-contexts', workspacesRoutes);
router.use('/navigation', navigationRoutes);
router.use('/public', publicContentRoutes);
router.use('/public/gigs', gigsRoutes);
router.use('/public/groups', groupsRoutes);
router.use('/public/videos', videosRoutes);
router.use('/public/talent', talentRouter);
router.use('/public/companies', companiesRouter);
router.use('/public/jobs', publicJobsRouter);
router.use('/public/posts', publicPostsRouter);
router.use('/public/billing', billingRoutes);
router.use('/billing', billingAuthRoutes);
router.use('/public/help-centre', helpCentreRoutes);
router.use('/public/legal', legalRoutes);
router.use('/public/resources', resourcesRoutes);
router.use('/public/personalization', personalizationRoutes);
router.use('/public/analytics', analyticsRoutes);
router.use('/saved-items', savedItemsRoutes);
router.use('/activity', activityRoutes);
router.use('/copilot', copilotRoutes);
router.use('/ads', adsRoutes);
router.use('/ai-actions', aiActionsRoutes);
router.use('/ai-tasks', aiTasksRoutes);
router.use('/ai-memory', aiMemoryRoutes);
router.use('/ai-personalisation', aiPersonalisationRoutes);
router.use('/ai-model-preferences', aiModelPreferencesRoutes);
router.use('/ai-usage', aiUsageRoutes);
router.use('/ai-audit', aiAuditRoutes);
router.use('/ai-prompts', aiPromptsRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/imports', importsRoutes);
router.use('/contacts', contactsRoutes);
router.use('/setup-checklist', setupChecklistRoutes);
router.use('/product-tour', productTourRoutes);
router.use('/tasks', tasksRoutes);
router.use('/calendar', calendarRoutes);
router.use('/projects', projectsRoutes);
router.use('/pm-projects', pmProjectsRoutes);
router.use('/disputes', disputesRoutes);
router.use('/job-alerts', jobAlertsRoutes);
router.use('/screening', screeningRoutes);
router.use('/assessments', assessmentsRoutes);
router.use('/interviews', interviewsRoutes);
router.use('/offers', offersRoutes);
router.use('/sponsored-jobs', sponsoredJobsRoutes);
router.use('/hire-handoffs', hireHandoffsRoutes);
router.use('/podcasts', podcastsRoutes);
router.use('/webinars', webinarsRoutes);
router.use('/articles', articlesRoutes);
router.use('/newsletters', newslettersRoutes);
router.use('/hashtags', hashtagsRoutes);
router.use('/trending', trendingRoutes);
router.use('/professional-profile', professionalProfileRoutes);
router.use('/admin', adminRoutes);
router.use('/admin/moderation', moderationRoutes);

export default router;
