// Registry of the 28 Domain 02 public pages. Backs the technical-context
// footer shown only in TECHNICAL_REVIEW_MODE (see TechnicalContextFooter) —
// never rendered for ordinary production visitors.
export type PublicPageId =
  | '02.01' | '02.02' | '02.03' | '02.04' | '02.05' | '02.06' | '02.07' | '02.08'
  | '02.09' | '02.10' | '02.11' | '02.12' | '02.13' | '02.14' | '02.15' | '02.16'
  | '02.17' | '02.18' | '02.19' | '02.20' | '02.21' | '02.22' | '02.23' | '02.24'
  | '02.25' | '02.26' | '02.27' | '02.28';

export type PublicPageMeta = {
  id: PublicPageId;
  name: string;
  type: string;
  route: string;
  coreComponents: string;
  primaryData: string;
  realtime: string;
  aiMl: string;
};

export const PUBLIC_PAGE_REGISTRY: Record<PublicPageId, PublicPageMeta> = {
  '02.01': { id: '02.01', name: 'Home', type: 'Main public page', route: '/home', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.02': { id: '02.02', name: 'For Professionals', type: 'Marketing page', route: '/for-professionals', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.03': { id: '02.03', name: 'For Businesses', type: 'Marketing page', route: '/for-businesses', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.04': { id: '02.04', name: 'Recruiter', type: 'Product page', route: '/app/recruiter', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.05': { id: '02.05', name: 'Recruiter Pro', type: 'Upgrade page', route: '/app/recruiter-pro', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.06': { id: '02.06', name: 'Sales Navigator', type: 'Product page', route: '/app/sales-navigator', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.07': { id: '02.07', name: 'Enterprise Connect', type: 'Product page', route: '/app/enterprise-connect', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.08': { id: '02.08', name: 'Experience Launchpad', type: 'Product page', route: '/app/experience-launchpad', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.09': { id: '02.09', name: 'Gigs Marketplace', type: 'Public collection', route: '/gigs-marketplace', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.10': { id: '02.10', name: 'Jobs Marketplace', type: 'Public collection', route: '/jobs-marketplace', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.11': { id: '02.11', name: 'Talent Directory', type: 'Public collection', route: '/talent-directory', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.12': { id: '02.12', name: 'Company Directory', type: 'Public collection', route: '/company-directory', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.13': { id: '02.13', name: 'Groups Directory', type: 'Public collection', route: '/groups-directory', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.14': { id: '02.14', name: 'Video Explore', type: 'Public collection', route: '/video-explore', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.15': { id: '02.15', name: 'Pricing', type: 'Marketing page', route: '/pricing', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.16': { id: '02.16', name: 'Enterprise', type: 'Marketing page', route: '/enterprise', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.17': { id: '02.17', name: 'About', type: 'Marketing page', route: '/about', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.18': { id: '02.18', name: 'Contact', type: 'Marketing page', route: '/contact', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.19': { id: '02.19', name: 'Help Centre', type: 'Public support', route: '/help-centre', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.20': { id: '02.20', name: 'Blog / Resources', type: 'CMS collection', route: '/app/blog--resources', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.21': { id: '02.21', name: 'Legal Index', type: 'Legal page', route: '/legal-index', coreComponents: 'App/Page shell + Page header + Responsive state container', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.22': { id: '02.22', name: 'Public Profile', type: 'Detail page', route: '/public-profile', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.23': { id: '02.23', name: 'Public Company Page', type: 'Detail page', route: '/public-company-page', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.24': { id: '02.24', name: 'Public Job', type: 'Detail page', route: '/public-job', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.25': { id: '02.25', name: 'Public Gig', type: 'Detail page', route: '/public-gig', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.26': { id: '02.26', name: 'Public Post', type: 'Detail page', route: '/public-post', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.27': { id: '02.27', name: 'Public Video', type: 'Detail page', route: '/public-video', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
  '02.28': { id: '02.28', name: 'Public Group', type: 'Detail page', route: '/public-group', coreComponents: 'App/Page shell + Page header + Responsive state container + Summary header + Tabbed detail body + Activity rail + Inline edit controls', primaryData: 'cms_pages + landing_variants + public_slugs', realtime: 'HTTP + event refresh', aiMl: 'Landing-page personalisation + Lead propensity scoring' },
};
